### ISSUE TITLE
Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by AnehEf** [AFIDSI/Covid19-Wastewater-Analysis#3]
Hi, 

While trying to install the package DSIWastewater using devtools, I kept getting the error below (I got the Personal access tokens) : 

```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`AFIDSI`) and repo name (`DSIWastewater`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```
  
  I also tried with "AFIDSI/Covid19-Wastewater-Analysis"
  I found the tar.gz, but in a private repo. 
  
  Thanks for your help, 
  Adelaide

**Comment by MarlinRLee** [comment]
Hi,

Looking into it both of those are caused by the package repo being set to private. I have made the package repo public to make it easier to access anything you might need. Now both methods should work without issue and you should not need the access token anymore.

Sorry for responding so late,
Marlin
